### ISSUE TITLE
TagCommander init crash on iOS 12, iOS Simulator, Macbook M1

### ISSUE THREAD

**Issue by celian-m** [TagCommander/pods#13]
I'm currently using the TagCommander SDK.

Until now it was working fine, but now I have an evolution on my app and the SDK is 100% crashing on my iOS 12 simulator.

My code is `let obj = TagCommander(siteID: XXXX, andContainerID: XX)`

It causes : 
**_Thread 1: EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)_**

I'm trying to check on a real device, but this is kind of blocking.

My Configuration is : 
  - latest-TCCore-Debug-universal-noIDFA (4.6.9)
  - latest-TCCore-Release-iphoneos-noIDFA (4.6.9)
  - latest-TCSDK-Debug-universal-noIDFA (4.5.6)
  - latest-TCSDK-Release-iphoneos-noIDFA (4.5.6)

(I have the crash with older version, so I updated it => Same result)

My workstation : 
MacBook Pro m1
cocoa pod 1.10.0
Xcode 12.4

Thanks for the help

**Comment by CommandersAct** [comment]
Hello !

My guess is that you recently changed from Xcode 11 to Xcode 12 right?
We created specific releases for XCode 12 which don't have a "latest" podspec for now.
They change a lot since we're now using XCFramework instead of lipo and this removes the need to have debug/release and non universal versions.

You can check in the changelog for those versions if needed.
The latest TCCore XCode 12 version is https://github.com/TagCommander/pods/tree/master/TCCore/4/7/4
The latest TCSDK is https://github.com/TagCommander/pods/tree/master/TCSDK/4/6/3
